#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'nodes==0.0.0','console_scripts','realsense_camera_node'
__requires__ = 'nodes==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('nodes==0.0.0', 'console_scripts', 'realsense_camera_node')()
    )
